In [1]:
import numpy as np
import sympy as sp

x1 = sp.Symbol("x1")
x2 = sp.Symbol("x2")
a = sp.Symbol("a")

f = np.linalg.multi_dot([1/2*np.array([x1,x2]),
                         np.array([[2,-3],[-3,5]]),
                         np.array([[x1],[x2]])]) - np.dot(np.array([x1,x2]),np.array([[0],[1]]))
ft = np.dot(np.array([[2,-3],[-3,5]]),np.array([[x1],[x2]])) - np.array([[0],[1]])
q = np.array([[2,-3],[-3,5]])
nilai_awal = [0,0]
h = np.identity(2)
error = 10**-6

def BFGS(ft):
    print("f'(x) =")
    print(ft)
    
    n = 1
    convergent = True
    condition = True
    while condition:
        print("\n----------------Iterasi {}----------------".format(n))
        if n >= 2:
            print("\ndelta x{} =".format(n - 2))
            delta_x = a_lama * d_lama
            print(delta_x)
        
        print("\ng{} =".format(n - 1))
        if n == 1:
            g = np.array([ft[0][0].subs({x1:nilai_awal[0],x2:nilai_awal[1]}),
                          ft[1][0].subs({x1:nilai_awal[0],x2:nilai_awal[1]})]).reshape(2,-1)
            print(g)
        else:
            g = np.array([ft[0][0].subs({x1:x_lama[0][0],x2:x_lama[1][0]}),
                          ft[1][0].subs({x1:x_lama[0][0],x2:x_lama[1][0]})]).reshape(2,-1)
            print(g)
                   
        if n >= 2:
            print("\ndelta g{} =".format(n - 2))
            delta_g = g - g_lama
            print(delta_g)
            
            pertama = 1 + np.divide(np.linalg.multi_dot([delta_g.transpose(),h,delta_g]),
                                    np.dot(delta_g.transpose(),delta_x))
            
            kedua = np.divide(np.dot(delta_x,delta_x.transpose()),
                              np.dot(delta_x.transpose(),delta_g))
            
            ketiga_1 = np.linalg.multi_dot([h,delta_g,delta_x.transpose()])
            ketiga_2 = ketiga_1.transpose()
            
            ketiga = np.divide(ketiga_1 + ketiga_2,np.dot(delta_g.transpose(),delta_x))
            
            print("\nH{} =".format(n - 1))
            h_baru = h + ((pertama[0][0])*kedua) - ketiga
            print(h_baru)

        if n == 1:
            print("\nd{} =".format(n - 1))
            d = np.dot(-1 * h,g)
            print(d)
        else:
            print("\nd{} =".format(n - 1))
            d = np.dot(-1 * h_baru,g)
            print(d)
    
        hasil_a = -1 * np.divide(np.dot(g.transpose(),d),
                                 np.dot(np.dot(d.transpose(),q),d))[0][0]
        print("\na{} = {}".format(n - 1,hasil_a))

        print("\nx{} =".format(n))
        if n == 1:
            x = np.array(nilai_awal).reshape(2,-1) + hasil_a*d
            print(x)
        else:
            x = np.array(x_lama).reshape(2,-1) + hasil_a*d
            print(x)
        
        if n > 1:
            if (g[0][0] < error) & (g[1][0] < error):
                g = np.array([0,0]).reshape(2,-1)
                print("\ng{} =".format(n))
                print(g)
                print("\nKarena g{} = 0, proses perhitungan dihentikan.".format(n))
                break
            elif np.linalg.det(h_baru) < error:
                print("\nKarena matriks H tidak definit positif, proses perhitungan dihentikan.")
            elif (abs((x_lama - x)[0][0]) < error) & (abs((x_lama - x)[1][0]) < error):
                print("\nabs(x{} - x{}) =".format(n,n-1))
                print(x_lama - x)
                print("\nKarena abs(x{} - x{}) < {}, proses perhitungan dihentikan.".format(n,n-1,error))
                condition = False
        
        if n > 100:
            convergent = False
            break

        x_lama = x
        g_lama = g
        d_lama = d
        a_lama = hasil_a
        n += 1

    nilai_minimum = f[0].subs({x1:x[0][0],x2:x[1][0]})
    print("\nNilai minimum f adalah {}".format(nilai_minimum))
            
BFGS(ft)

f'(x) =
[[2*x1 - 3*x2]
 [-3*x1 + 5*x2 - 1]]

----------------Iterasi 1----------------

g0 =
[[0]
 [-1]]

d0 =
[[0]
 [1.00000000000000]]

a0 = 0.200000000000000

x1 =
[[0]
 [0.200000000000000]]

----------------Iterasi 2----------------

delta x0 =
[[0]
 [0.200000000000000]]

g1 =
[[-0.600000000000000]
 [0]]

delta g0 =
[[-0.600000000000000]
 [1]]

H1 =
[[1.00000000000000 0.600000000000000]
 [0.600000000000000 0.560000000000000]]

d1 =
[[0.600000000000000]
 [0.360000000000000]]

a1 = 5.00000000000000

x2 =
[[3.00000000000000]
 [2.00000000000000]]

g2 =
[[0]
 [0]]

Karena g2 = 0, proses perhitungan dihentikan.

Nilai minimum f adalah -1.00000000000000
